### ISSUE TITLE
MethodError: no method matching reducedim_init

### ISSUE THREAD

**Issue by fedario** [TuringLang/DistributionsAD.jl#43] opened 2020-03-15 23:49 UTC
When I try to take the gradient of this loss function:

```Julia
function lossfn(mbatch)
    posterior_fn = encoder(mbatch)
    sample = hcat(rand.(posterior_fn)...)
    likelihood_fn = decoder(sample)

    elbos = (
        DistributionsAD.logpdf.(likelihood_fn, eachcol(mbatch))
        + DistributionsAD.logpdf.([prior_fn], eachcol(sample))
        - DistributionsAD.logpdf.(posterior_fn, eachcol(sample))
    )
    mean(elbos)
end
```

```Julia
params = Flux.params(encoder, decoder)
gradients = gradient(() -> lossfn(mbatch), params)
```

I get this error:

```
ERROR: MethodError: no method matching reducedim_init(::typeof(identity), ::typeof(Zygote.accum), ::Array{NamedTuple{(:m, :σ),Tuple{Array{Float64,1},Array{Float64,1}}},1}, ::Tuple{Int64})
Closest candidates are:
  reducedim_init(::Any, ::Union{typeof(+), typeof(Base.add_sum)}, ::AbstractArray, ::Any) at reducedim.jl:109
  reducedim_init(::Any, ::Union{typeof(*), typeof(Base.mul_prod)}, ::AbstractArray, ::Any) at reducedim.jl:112
  reducedim_init(::Any, ::typeof(min), ::AbstractArray, ::Any) at reducedim.jl:132
  ...
```

Any ideas?

**Comment by mohamed82008** [comment] 2020-03-16 00:02
Please make sure your example is runnable. `prior_fn`, `encoder`, `decoder` and `mbatch` are not defined.

**Comment by fedario** [comment] 2020-03-16 00:20
Here is a runnable example:

```Julia
using DistributionsAD
using IterTools
using Statistics
using Flux


struct NNCondDist
    input_dims::Integer
    dist_dims::Integer
    network
end

Flux.@functor NNCondDist

function NNCondDist(input_dims::Integer, dist_dims::Integer, num_layers::Integer)
    num_dist_params = 2
    sizes = Int.(
        round.(
            range(input_dims, dist_dims * num_dist_params, length=num_layers + 1)
        )
    )

    network = []
    for (insize, outsize) in IterTools.partition(sizes, 2, 1)
        if outsize != dist_dims * num_dist_params
            push!(network, Dense(insize, outsize, relu))
        else
            push!(network, Dense(insize, outsize))
        end
    end

    NNCondDist(
        input_dims,
        dist_dims,
        Chain(network...),
    )
end

function (nn_cond_dist::NNCondDist)(data)
    params = nn_cond_dist.network(data)
    μ = params[1:nn_cond_dist.dist_dims, :]
    σ = softplus.(params[nn_cond_dist.dist_dims + 1:end, :])
    TuringDiagMvNormal.(eachcol(μ), eachcol(σ))
end

function lossfn(mbatch)
    posterior_fn = encoder(mbatch)
    sample = hcat(rand.(posterior_fn)...)
    likelihood_fn = decoder(sample)

    elbos = (
        DistributionsAD.logpdf.(likelihood_fn, eachcol(mbatch))
        + DistributionsAD.logpdf.([prior_fn], eachcol(sample))
        - DistributionsAD.logpdf.(posterior_fn, eachcol(sample))
    )
    mean(elbos)
end

obs_dims = 50
latent_dims = 3

encoder = NNCondDist(obs_dims, latent_dims, 3)
decoder = NNCondDist(latent_dims, obs_dims, 3)

prior_fn = TuringDiagMvNormal(zeros(latent_dims), ones(latent_dims))

mbatch = rand(50, 2)

params = Flux.params(encoder, decoder)
gradients = gradient(() -> lossfn(mbatch), params)
```

**Comment by mohamed82008** [comment] 2020-03-16 05:52
I made a PR with a fix. It will be merged and released soon.

**Closed** 2020-03-16 08:32 UTC

**Comment by fedario** [comment] 2020-03-19 10:58
Unfortunately, I'm still experiencing the same error on master.

**Comment by mohamed82008** [comment] 2020-03-21 09:54
Hmm do you know why it is not working with Flux.gradient? Perhaps ask the Flux folks.

**Comment by mohamed82008** [comment] 2020-03-21 09:55
If the problem is a Zygote-support problem, please reopen this.
